services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/usr/src/app/backend
    working_dir: /usr/src/app/backend
    environment:
      DATABASE_URL: postgres://user:password@database:5432/project_db
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
    working_dir: /usr/src/app/frontend

  database:
    image: postgres:latest
    container_name: pg_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  cargo-cache:
  db_data:
